#pragma once
#include <stdlib.h>
/* Machine generated by gen_authors.sh */
static const char *brisk_developers[] = {
        "Federico Damián Schonborn <federicodamiansch@gmail.com>",
        "Ikey Doherty <ikey@solus-project.com>",
        "Martin Wimpress <code@flexion.org>",
        "Stefan Ric <stfric369@gmail.com>",
        "Victor Kareh <vkareh@vkareh.net>",
        NULL,
};
